# name: Publish Package to npmjs

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       # Setup .npmrc file to publish to npm
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '20.x'
#           registry-url: https://npm.pkg.github.com/
#           # Defaults to the user or organization that owns the workflow file
#           scope: 'sherpasdev'
#       - run: yarn
#       - run: echo ${{ secrets }}
#       - run: yarn publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

name: Publish my node package

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # allow GITHUB_TOKEN to publish packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: "https://npm.pkg.github.com/vitaliinamys"
